# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'devopsdemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for devopsdemo
  pod 'AppCenter'
  pod 'AppCenter/Analytics'
  pod 'AppCenter/Crashes'
  pod 'SnapKit'
end
